- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_fqdn: ngobox.robertnclayton.net
  remote_user: ubuntu
  become: true
  gather_facts: false
  module_defaults:
    apt:
      force_apt_get: true

  tasks:
    
    - name: Set links in nextcloud "external sites" to Nodered, CouchDB, and phpList...
      become_user: www-data
      shell: php occ config:app:set external sites --value='{"1":{"icon":"external.svg","lang":"","type":"link","device":"","groups":["admin"],"redirect":false,"id":1,"name":"CouchDB","url":"https:\/\/{{ ansible_fqdn }}\/couchdb\/_utils\/#login"},"2":{"icon":"external.svg","lang":"","type":"link","device":"","groups":["admin"],"redirect":false,"id":2,"name":"NodeRed","url":"https:\/\/{{ ansible_fqdn }}\/nodered"},"3":{"id":3,"name":"phpList","url":"https:\/\/{{ ansible_fqdn }}\/lists\/admin\/","lang":"","type":"link","device":"","icon":"external.svg","groups":["admin"],"redirect":false}}'
      args:
        chdir: /var/www/nextcloud
